accounts/urls.py
from django.urls import path
from . import views
from . import api
app_name ='accounts'
urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile',views.user_profile,name='profile'),
    path('profile/jobs',views.user_posted_jobs,name='profile_jobs'),
    path('profile/job/owner/<int:pk>',views.job_posted_profile,name='job_posted_by'),
    path('profile/job/applicants/<int:pk>',views.job_applicants,name='job_applicants'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
    
    
    #rest api 
    path('rest/profiles',api.FBV_Profile,name = "FBV_Profile"),
    
]

job/urls.py
from django.urls import path
from . import views

app_name ='job'

urlpatterns = [
    path('',views.all_jobs,name='all_jobs'),
    path('add', views.add_job,name='add_job'),
    path('<str:slug>', views.job_details,name='job_details'),
    

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',include('job.urls',namespace='job')),
    path('contact-us/',include('contact.urls',namespace='contact')),


]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User
from accounts.models import profile

# Create your models here.
JOB_TYPE = (
    ('Full_Time','Full_Time'),
    ('Part_Time','Part_Time'),
)

GENDER  = (
    ('MALE','MALE'),
    ('FEMALE','FEMALE'),
)
category_options = (
    ("programming","Programming"),
    ("agriculture", "Agreculture"),
    ("science","Science"),
)
def image_save(instance,filename):
    image_name,extinsion = filename.split('.')
    return "jobs/%s.%s"%(instance.id,extinsion)
    
class job(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE )
    title = models.CharField(max_length=100)
    # locatoin ...  
    profile_name = models.ForeignKey(profile, on_delete = models.CASCADE, related_name ="job" )
    type = models.CharField(max_length=100,choices=JOB_TYPE)
    description = models.TextField(max_length=1000)
    puplished_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary = models.IntegerField(default=0)
    category_name = models.CharField(max_length = 50 , choices =category_options, null = True, blank = True )
    experience = models.IntegerField(default=1)
    gender = models.CharField(max_length=100,choices=GENDER) 
    image = models.ImageField(upload_to=image_save)
    slug = models.SlugField(blank=True,null=True)


    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)  
        super(job,self).save(*args,**kwargs)
        
    def __str__(self):
        return self.title


class Apply(models.Model):
    apply_job = models.ForeignKey(job,on_delete=models.CASCADE, related_name="apply")
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=50)
    portfolio = models.URLField()
    cv = models.FileField(upload_to="apply/")
    coverletter = models.TextField(max_length=1000)
    apply_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

job/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import job
from accounts.models import profile
from django.core.paginator import Paginator
from .form import ApplyForm ,AddJob
from django.contrib.auth.decorators import login_required 
from .filters import JobFilter
from django.core.mail import send_mail
from django.contrib import messages
from django.conf import settings




# Create your views here.
def all_jobs(request):
    all_jobs = job.objects.all().order_by('-puplished_at')
    filter = JobFilter(request.GET,queryset=all_jobs)
    all_jobs = filter.qs
    num = job.objects.all().order_by("-puplished_at")[:3]
    num1 = job.objects.all().count()
    data_per_page = Paginator(all_jobs,3)#this line will appear only on job in each page
    page_num = request.GET.get("page")
    page_obj = data_per_page.get_page(page_num)
    context = {'jobs':page_obj, 'num':num,'num1':num1,'filter':filter}
    return render(request,'job/jobs.html',context)

@login_required
def job_details(request,slug):
    one_job = job.objects.get(slug=slug)
    if request.method == "POST":
        form = ApplyForm(request.POST, request.FILES)
        if form.is_valid():
            my_job = form.save(commit=False)
            my_job.apply_job = one_job
            my_job.save()
    else:
        form=ApplyForm()

    context = {'job':one_job,'form':form}
    return render(request,'job/job_details.html',context)


@login_required
def add_job(request):
    if request.method =="POST":
        form = AddJob(request.POST, request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.profile_name = profile.objects.get(user=request.user)
            myform.save()
            return redirect(reverse("job:all_jobs"))
    else:
        form=AddJob()
    
    return render(request,"job/add_job.html",{'form':form})

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
   

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    
                    <div class="apply_job_form white-bg">
                        <h4 class="text-center">Post New Job </h4>
                        <form method="post" class="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form layout='horizontal' %}
                            {% buttons %}
                            <button class="boxed-btn3 w-100" type="submit">Post Now</button>    
                            {% endbuttons %}
                        </form>                        
                    </div>
                </div>
               
            </div>
        </div>
    </div>

   {% endblock %}

job/templates/job/job_details.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
   

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="{{job.image.url}}" alt="" height="80px" width="80px" >
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i>{{job.puplished_at}}</p>
                                            <p><i class="fa fa-book"></i>Published By/<a href="{% url 'accounts:job_posted_by' job.pk %}"> {{job.profile_name.user.first_name}}  {{job.profile_name.user.last_name}}</a> </p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                           
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.description}}</p>
                        </div>
                       
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                            <form  method="post" class="form" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form form %}
                                {% buttons %}
                                <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                              {% endbuttons %}
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.puplished_at|date:'l d M o'}}</span></li>
                                <li>Vacancy: <span>{{job.vacancy}} Position</span></li>
                                <li>Salary: <span>{{job.salary}} /M</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span>{{job.type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>

   {% endblock %}

job/templates/job/jobs.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% load static %}


{% block content %}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{num1}}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form filter.form  %} 
                                    <button  class="boxed-btn3 w-100  mt-2" type="submit">search</button>
                               </form>
                        </div>
                        
                     
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select onchange="location=this.value;">
                                            <option  data-display="Most Recent">Most Recent</option>
                                            {% for job in num %}
                                            <option value="{% url 'job:job_details' job.slug %} ">{{ job.title }}</option>
                                            {% endfor %}
                                            
                                        </select>
                                       
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in jobs %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="{{job.image.url}}" alt="" height="80px" width="80px">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'job:job_details' job.slug %}"><h4>{{job.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a href="{% url 'job:job_details' job.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>{{job.puplished_at|date:'l d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% if jobs.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if jobs.has_previous %}
                                        <li><a href="?page={{ jobs.previous_page_number }}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}
                                        {% for i in jobs.paginator.page_range %}
                                        <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}
                                        {% if jobs.has_next %}
                                        <li><a href="?page={{ jobs.next_page_number }}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock %}