accounts/urls.py
from django.urls import path
from . import views
from . import api
app_name ='accounts'
urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile',views.user_profile,name='profile'),
    path('profile/jobs',views.user_posted_jobs,name='profile_jobs'),
    path('profile/job/owner/<int:pk>',views.job_posted_profile,name='job_posted_by'),
    path('profile/job/applicants/<int:pk>',views.job_applicants,name='job_applicants'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
    
    
    #rest api 
    path('rest/profiles',api.FBV_Profile,name = "FBV_Profile"),
    
]

job/urls.py
from django.urls import path
from . import views

app_name ='job'

urlpatterns = [
    path('',views.all_jobs,name='all_jobs'),
    path('add', views.add_job,name='add_job'),
    path('<str:slug>', views.job_details,name='job_details'),
    

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',include('job.urls',namespace='job')),
    path('contact-us/',include('contact.urls',namespace='contact')),


]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE )
    city = models.ForeignKey('city',on_delete=models.CASCADE,null=True,blank=True)
    image = models.ImageField(upload_to='profile/',null=True,blank=True,default='avatar.jpg')
    phone_number = models.PositiveIntegerField(null=True)

    def __str__(self):
        return str(self.user)



@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile.objects.create(user=instance)

class city(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return str(self.name)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import profile


class signupfrom(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username','first_name','last_name','email','password1','password2']

class profileform(forms.ModelForm):
    class Meta:
        model = profile
        exclude =('user',)

class userform(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email']

accounts/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from .forms import signupfrom ,profileform ,userform
from .models import profile
from django.contrib.auth import authenticate,login
from job.models import job

# Create your views here.



def signup(request):
    if request.method=='POST':
        form = signupfrom(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')
    else:
        form = signupfrom()
    return render (request,'registration/signup.html',{'form':form})
                


def user_profile(request):
    Profile= profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':Profile})



def job_posted_profile(request,pk):
    selected_job= job.objects.get(pk = pk)
    profile_1 = selected_job.profile_name
    Profile= profile.objects.get(user=request.user)
    if(Profile == profile_1):
            return render(request,'accounts/profile.html',{'profile':Profile})    
    return render(request,'accounts/profile_custom_view.html',{'profile':selected_job.profile_name})


def job_applicants(request,pk):
    selected_job= job.objects.get(pk = pk)
    applicants = selected_job.apply.all()
    return render(request,'accounts/job_applicants.html',{'applicants':applicants})



def user_posted_jobs(request):
    Profile= profile.objects.get(user=request.user)
    posted_jobs = Profile.job.all()
    return render(request,'accounts/pofile_posted_jobs.html',{'profile':Profile, 'posted':posted_jobs})


def profile_edit(request):
    Profile= profile.objects.get(user=request.user)
    if request.method=='POST':
       profile_form=profileform(request.POST,request.FILES,instance=Profile)
       user_form=userform(request.POST,instance=request.user) 
       if  profile_form.is_valid() and user_form.is_valid():
           user_form.save()
           profile_form.save(commit=False)
           profile_form.user=request.user
           profile_form.save() 
           return redirect(reverse('accounts:profile'))

    else:
        profile_form=profileform(instance=Profile)
        user_form=userform(instance=request.user)

    return render(request,'accounts/profile_edit.html',{"profileform":profile_form,'userform':user_form})

accounts/templates/accounts/job_applicants.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
   

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_details_header">
                                
                                    <div class="job_sumary ">
                                        <div class="summery_header ">
                                            <h2 class="text-center">Job Applicants</h2>
                                        </div>
                                        <div class="job_content">
                                           
                                            <ul>
                                            {% for item in applicants %}
                                                <li>name <strong style="color: black;"> {{item.name}}</strong> </li>
                                                <li>Email <strong style="color: black;"> {{item.email}}</strong> </li>
                                                <li>Portfolio <strong style="color: black;"> {{item.portfolio}}</strong> </li>
                                                <li>CV <strong style="color: black;"><a href="{{item.cv.url}}" target="_blank" class="boxed-btn3 w-20 " > {{item.name}} CV </a> </strong> </li>
                                                <li>Cover letter <strong style="color: black;"> {{item.coverletter}}</strong> </li>
                                                <li>Applied At <strong style="color: black;"> {{item.apply_at}}</strong> </li>
                                                <hr>
                                            {% endfor %}
                                            </ul>
                                        </div>
                        
                                </div>
                                
                            </div>
                           
                        </div>
                    </div>
                
                    
                </div>
             
            </div>
        </div>
    </div>

   {% endblock %}

accounts/templates/accounts/pofile_posted_jobs.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
   

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Welcom {{profile.user}} ^^</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_details_header">
                                
                                    <div class="job_sumary ">
                                        <div class="summery_header ">
                                            <h2 class="text-center">{{profile.user}} Posted jobs</h2>
                                        </div>
                                        <div class="job_content">
                                           
                                            <ul>
                                            {% for item in posted %}
                                                <li><span><strong><a href= "{% url 'job:job_details' item.slug %}"> {{item.title}} <img src="{{item.image.url}}" alt="" height="80px" width="80px" >
                                                </strong></span></li>
                                                <br> <br>
                                             <a href="{% url 'accounts:job_applicants' item.pk %}" class="boxed-btn3 w-100">Applications</a> <br> <br>

                                            {% endfor %}
                                            </ul>
                                        </div>
                        
                                </div>
                                
                            </div>
                           
                        </div>
                    </div>
                
                    
                </div>
             
            </div>
        </div>
    </div>

   {% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
   

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Welcom {{profile.user}} ^^</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_details_header">
                                
                                    <div class="job_sumary ">
                                        <div class="summery_header ">
                                            <h2 class="text-center">{{profile.user.first_name}} {{profile.user.last_name}}</h2>
                                        </div>
                                        <div class="job_content">
                                           
                                            <ul>
                                            
                                               <li><img src="{{profile.image.url}}" height="200px" width="200px" ></li>
                                                <li>Name: <span><strong>{{profile.user}}</strong></span></li>
                                                <li>Email: <span><strong>{{profile.user.email}}</strong></span></li>
                                                <li>City: <span><strong>{{profile.city}}</strong></span></li>
                                                <li>Phone Number: <span><strong>{{profile.phone_number}}</strong></span></li>
                                            </ul>
                                        </div>
                                          <div>
                                             <a href="{% url 'accounts:profile_edit' %}" class="boxed-btn3 w-100">Edit Profile</a>
                                         </div>
                                  
                                   
                                </div>
                                
                            </div>
                           
                        </div>
                    </div>
                
                    
                </div>
             
            </div>
        </div>
    </div>

   {% endblock %}

accounts/templates/accounts/profile_custom_view.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
   

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Publisher Info </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_details_header">
                                
                                    <div class="job_sumary ">
                                        <div class="summery_header ">
                                            <h2 class="text-center">{{profile.user.first_name}} {{profile.user.last_name}}</h2>
                                        </div>
                                        <div class="job_content">
                                           
                                            <ul>
                                            
                                               <li><img src="{{profile.image.url}}" height="200px" width="200px" ></li>
                                                <li>Name: <span><strong>{{profile.user.first_name}} {{profile.user.last_name}}</strong></span></li>
                                                <li>Email: <span><strong>{{profile.user.email}}</strong></span></li>
                                                <li>City: <span><strong>{{profile.city}}</strong></span></li>
                                                <li>Phone Number: <span><strong>{{profile.phone_number}}</strong></span></li>
                                               
                                            </ul>
                                        </div>
                                   
                                </div>
                                
                            </div>
                           
                        </div>
                    </div>
                
                    
                </div>
             
            </div>
        </div>
    </div>

   {% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
   

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Edit Profile</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
      
                <div class="col-lg-10 mx-auto">
                    
                    <div class="apply_job_form white-bg">
                        <h4>Edit Your Profile </h4>
                        <form method="post" class="form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform layout='horizontal' %}
                            {% bootstrap_form profileform layout='horizontal' %}
                            <br>
                            {% buttons %}
                            <button class="boxed-btn3 w-100" type="submit">Save</button>    
                            {% endbuttons %}
                        </form>                        
                    </div>
                </div>
               
            </div>
        </div>
    </div>

   {% endblock %}