accounts/urls.py
from django.urls import path
from . import views
from . import api
app_name ='accounts'
urlpatterns = [
    path('signup',views.signup,name='signup'),
    path('profile',views.user_profile,name='profile'),
    path('profile/jobs',views.user_posted_jobs,name='profile_jobs'),
    path('profile/job/owner/<int:pk>',views.job_posted_profile,name='job_posted_by'),
    path('profile/job/applicants/<int:pk>',views.job_applicants,name='job_applicants'),
    path('profile/edit',views.profile_edit,name='profile_edit'),
    
    
    #rest api 
    path('rest/profiles',api.FBV_Profile,name = "FBV_Profile"),
    
]

contact/urls.py
from django.urls import path
from . import views

app_name='contact'
urlpatterns = [

    path('contact',views.contact,name='contact'),
    path('subscribe/', views.subscribe, name='subscribe'),

]

job/urls.py
from django.urls import path
from . import views

app_name ='job'

urlpatterns = [
    path('',views.all_jobs,name='all_jobs'),
    path('add', views.add_job,name='add_job'),
    path('<str:slug>', views.job_details,name='job_details'),
    

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('',include('job.urls',namespace='job')),
    path('contact-us/',include('contact.urls',namespace='contact')),


]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.png'%}">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/slicknav.css'%}">

    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>
<body>
 <!-- header-start -->
 <header>
    <div class="header-area ">
        <div id="sticky-header" class="main-header-area">
            <div class="container-fluid ">
                <div class="header_bottom_border">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-2">
                            <div class="logo">
                                <a href="{% url 'job:all_jobs' %}">
                                    <img src="{% static 'img/logo.png'%}" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a href="{% url 'job:all_jobs' %}">Browse Job</a></li>
                                        <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                            <div class="Appointment">
                                
                                {% if request.user.is_authenticated %}
                                <div class="phone_num d-none d-xl-block">
                                    <a href="{% url 'logout' %}">Log Out</a>
                                </div>
                                <div class="phone_num d-none d-xl-block">
                                    <a href="{% url 'accounts:profile' %}">My Profile</a>
                                </div>
                                {% else %}
                                <div class="phone_num d-none d-xl-block">
                                    <a href="{% url 'login' %}">Log in</a>
                                </div>
                                <div class="phone_num d-none d-xl-block">
                                    <a href="{% url 'accounts:signup' %}">Sign Up</a>
                                </div>
                                {% endif %}                                   
                                <div class="d-none d-lg-block">
                                    <a class="boxed-btn3" href="{% url 'job:add_job' %}">Post a Job</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</header>
<!-- header-end -->
{% block content %}

{% endblock %}
{% if messages %}
      {% for message in messages %}
      <div class="alert alert-primary">
        <strong>{{ message }}</strong>
      </div>
        {% endfor %}
      {% endif %}

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="{% url 'job:all_jobs' %}">
                                    <img src="{% static 'img/logo.png'%}" alt="">
                                </a>
                            </div>
                            <p>
                                rahmahamoda59@gmail.com</a> <br>
                                (+2) 0101121459 <br>
                                El-shohada, Menofia
                            </p>
                           
                        </div>
                    </div>
                   
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="{% url 'contact:subscribe' %}" method="POST" class="newsletter_form">
                            {%csrf_token%}
                                <input type="text" placeholder="Enter your mail" name ="r_email">
                                <button type="submit" >Subscribe</button>
                            </form>
                            <p class="newsletter_text">It's Nice To See You Around ^^</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <script src="{% static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/isotope.pkgd.min.js'%}"></script>
    <script src="{% static 'js/ajax-form.js'%}"></script>
    <script src="{% static 'js/waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{% static 'js/scrollIt.js'%}"></script>
    <script src="{% static 'js/jquery.scrollUp.min.js'%}"></script>
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/nice-select.min.js'%}"></script>
    <script src="{% static 'js/jquery.slicknav.min.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>
    <!-- <script src="{% static 'js/gijgo.min.js'%}"></script> -->
    <script src="{% static 'js/range.js'%}"></script>



    <!--contact js-->
    <script src="{% static 'js/contact.js'%}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{% static 'js/jquery.form.js'%}"></script>
    <script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/mail-script.js'%}"></script>


    <script src="{% static 'js/main.js'%}"></script>


	<script>
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>

templates/base_generic.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
   

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    
                 {% block body  %}
                 {% endblock %}
                </div>
               
            </div>
        </div>
    </div>

   {% endblock %}